[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
# decorations = "buttonless"
decorations = "none"

[font]
normal = { family = "BlexMono Nerd Font Mono", style = "Regular" }
bold.style = "SemiBold"
italic.style = "Light Italic"
bold_italic.style = "Semibold Italic"
size = 14.0

[general]
import = ["~/.config/alacritty/themes/carbonfox.toml"]
